/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class andraus_bluetoothhidemu_spoof_jni_BluetoothSocketJni */

#ifndef _Included_andraus_bluetoothhidemu_spoof_jni_BluetoothSocketJni
#define _Included_andraus_bluetoothhidemu_spoof_jni_BluetoothSocketJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     andraus_bluetoothhidemu_spoof_jni_BluetoothSocketJni
 * Method:    createL2capFileDescriptor
 * Signature: (ZZ)I
 */
JNIEXPORT jint JNICALL Java_andraus_bluetoothhidemu_spoof_jni_BluetoothSocketJni_createL2capFileDescriptor
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     andraus_bluetoothhidemu_spoof_jni_BluetoothSocketJni
 * Method:    readBluetoothDeviceClass
 * Signature: ()[I
 */
    JNIEXPORT jintArray JNICALL Java_andraus_bluetoothhidemu_spoof_jni_BluetoothSocketJni_readBluetoothDeviceClass
      (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
